"""4

Revision ID: c5f9131d0bef
Revises: eedfa9147f07
Create Date: 2023-07-24 17:50:46.014453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f9131d0bef'
down_revision = 'eedfa9147f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
