"""3

Revision ID: eedfa9147f07
Revises: 8fd822955b13
Create Date: 2023-07-24 16:54:26.933567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedfa9147f07'
down_revision = '8fd822955b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openweather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('openweather_city_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'])
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openweather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('openweather_city_fkey', 'cities', ['city'], ['id'])
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
